server:
  # build: .
  image: dockerfile/nodejs-bower-gulp-runtime
  ports:
   - "8000:80"
  links:
   - "rethinkdb"
  environment:
    NODE_ENV: docker-local
    PORT: 80
rethinkdb:
  image: dockerfile/rethinkdb
  ports:
   - "8080:8080"
   - "28015:28015"
   - "29015:29015"